---
name: Nightly build CI

on:
  push:
    paths:
      - .github/workflows/nightly.yml
      - Dockerfile.client.production
      - Dockerfile.server.production
      - apps/client/**
      - apps/server/**
      - yarn.lock
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: medformatik/your_tidal # required dummy value, will not be used

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client nightly
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.client.production
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.docker-meta.outputs.labels }}
          tags: |
            medformatik/your_tidal_client:nightly
            medformatik/your_tidal_client:${{ github.sha }}
            ghcr.io/medformatik/your_tidal_client:nightly
            ghcr.io/medformatik/your_tidal_client:${{ github.sha }}

      - name: Build and push server nightly
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.server.production
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.docker-meta.outputs.labels }}
          tags: |
            medformatik/your_tidal_server:nightly
            medformatik/your_tidal_server:${{ github.sha }}
            ghcr.io/medformatik/your_tidal_server:nightly
            ghcr.io/medformatik/your_tidal_server:${{ github.sha }}
